version: "3"

services:
  postgres:
    image: postgres:12.4
    container_name: local_postgresql
    command:
      "-c log_statement=all"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
        - 80:80
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./test.sql:/test.sql